=== ZenFrogStudio/Ninja/bar/resources/zpack-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Ninja widget pack",
  "description": "A widget pack for Ninja.",
  "type": "object",
  "required": ["name", "version", "widgets"],
  "properties": {
    "name": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "previewImages": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "repositoryUrl": {
      "type": "string"
    },
    "widgets": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "htmlPath",
          "zOrder",
          "shownInTaskbar",
          "focused",
          "resizable",
          "transparent",
          "presets"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "htmlPath": {
            "type": "string"
          },
          "zOrder": {
            "type": "string",
            "enum": ["top_most", "normal", "bottom_most"]
          },
          "shownInTaskbar": {
            "type": "boolean"
          },
          "focused": {
            "type": "boolean"
          },
          "resizable": {
            "type": "boolean"
          },
          "transparent": {
            "type": "boolean"
          },
          "includeFiles": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "caching": {
            "type": "object",
            "properties": {
              "defaultDuration": {
                "type": "integer"
              },
              "rules": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "urlRegex": {
                      "type": "string"
                    },
                    "duration": {
                      "type": "integer"
                    }
                  }
                }
              }
            }
          },
          "privileges": {
            "type": "object",
            "properties": {
              "shellCommands": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "program": {
                      "type": "string"
                    },
                    "argsRegex": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "presets": {
            "type": "array",
            "items": [
              {
                "type": "object",
                "required": [
                  "name",
                  "anchor",
                  "offsetX",
                  "offsetY",
                  "width",
                  "height",
                  "monitorSelection"
                ],
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "anchor": {
                    "type": "string",
                    "enum": [
                      "top_left",
                      "top_center",
                      "top_right",
                      "center_left",
                      "center",
                      "center_right",
                      "bottom_left",
                      "bottom_center",
                      "bottom_right"
                    ]
                  },
                  "offsetX": {
                    "type": "string"
                  },
                  "offsetY": {
                    "type": "string"
                  },
                  "width": {
                    "type": "string"
                  },
                  "height": {
                    "type": "string"
                  },
                  "monitorSelection": {
                    "type": "object",
                    "oneOf": [
                      {
                        "properties": {
                          "type": {
                            "const": "all"
                          }
                        },
                        "required": ["type"],
                        "additionalProperties": false
                      },
                      {
                        "properties": {
                          "type": {
                            "const": "primary"
                          }
                        },
                        "required": ["type"],
                        "additionalProperties": false
                      },
                      {
                        "properties": {
                          "type": {
                            "const": "secondary"
                          }
                        },
                        "required": ["type"],
                        "additionalProperties": false
                      },
                      {
                        "properties": {
                          "type": {
                            "const": "index"
                          },
                          "match": {
                            "type": "integer",
                            "minimum": 0
                          }
                        },
                        "required": ["type", "match"],
                        "additionalProperties": false
                      },
                      {
                        "properties": {
                          "type": {
                            "const": "name"
                          },
                          "match": {
                            "type": "string"
                          }
                        },
                        "required": ["type", "match"],
                        "additionalProperties": false
                      }
                    ]
                  },
                  "dockToEdge": {
                    "type": "object",
                    "properties": {
                      "enabled": {
                        "type": "boolean",
                        "default": false
                      },
                      "edge": {
                        "oneOf": [
                          {
                            "type": "string",
                            "enum": ["top", "right", "bottom", "left"]
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "default": null
                      },
                      "windowMargin": {
                        "type": "string"
                      }
                    },
                    "additionalProperties": false
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

=== ZenFrogStudio/Ninja/bar/resources/starter/zpack.json
{
  "$schema": "https://github.com/glzr-io/zebar/raw/v3.0.0/resources/zpack-schema.json",
  "name": "starter",
  "version": "0.0.0",
  "description": "A basic widget pack for testing and development.",
  "tags": [
    "topbar"
  ],
  "previewImages": [
    "./resources/preview-image-1.png"
  ],
  "repositoryUrl": "",
  "widgets": [
    {
      "name": "vanilla",
      "htmlPath": "./vanilla.html",
      "zOrder": "normal",
      "shownInTaskbar": false,
      "focused": false,
      "resizable": false,
      "transparent": true,
      "includeFiles": [
        "*.html",
        "*.css",
        "*.png"
      ],
      "caching": {
        "defaultDuration": 604800,
        "rules": []
      },
      "privileges": {
        "shellCommands": []
      },
      "presets": [
        {
          "name": "default",
          "anchor": "top_left",
          "offsetX": "0px",
          "offsetY": "0px",
          "width": "100%",
          "height": "40px",
          "monitorSelection": {
            "type": "all"
          },
          "dockToEdge": {
            "enabled": false,
            "edge": null,
            "windowMargin": "0px"
          }
        }
      ]
    },
    {
      "name": "with-ninja",
      "htmlPath": "./with-ninja.html",
      "zOrder": "normal",
      "shownInTaskbar": false,
      "focused": false,
      "resizable": true,
      "transparent": true,
      "includeFiles": [
        "*.html",
        "*.css",
        "*.png"
      ],
      "caching": {
        "defaultDuration": 604800,
        "rules": []
      },
      "privileges": {
        "shellCommands": []
      },
      "presets": [
        {
          "name": "default",
          "anchor": "top_left",
          "offsetX": "0px",
          "offsetY": "0px",
          "width": "100%",
          "height": "40px",
          "monitorSelection": {
            "type": "all"
          },
          "dockToEdge": {
            "enabled": false,
            "edge": null,
            "windowMargin": "0px"
          }
        }
      ]
    },
    {
      "name": "with-komorebi",
      "htmlPath": "./with-komorebi.html",
      "zOrder": "normal",
      "shownInTaskbar": false,
      "focused": false,
      "resizable": true,
      "transparent": true,
      "includeFiles": [
        "*.html",
        "*.css",
        "*.png"
      ],
      "caching": {
        "defaultDuration": 604800,
        "rules": []
      },
      "privileges": {
        "shellCommands": []
      },
      "presets": [
        {
          "name": "default",
          "anchor": "top_left",
          "offsetX": "0px",
          "offsetY": "0px",
          "width": "100%",
          "height": "40px",
          "monitorSelection": {
            "type": "all"
          },
          "dockToEdge": {
            "enabled": false,
            "edge": null,
            "windowMargin": "0px"
          }
        }
      ]
    }
  ]
}
